#!/usr/bin/env bash
# bootstrap.sh — Prima Terminal Concept Bootstrap
# Idempotent: safe to run more than once.

set -euo pipefail

PRIMA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DOTFILES_DIR="$PRIMA_DIR/seeds/dotfiles"

echo "==> Prima Terminal: bootstrapping..."

# ---------------------------------------------------------------------------
# 1. Package installation
# ---------------------------------------------------------------------------
# Reads seeds/packages.yaml and installs required packages.
# Modify this section to match your package manager (pkg, apt, brew, etc.).

if command -v pkg &>/dev/null; then
    MANAGER="pkg"
elif command -v apt-get &>/dev/null; then
    MANAGER="apt-get"
else
    echo "WARN: No supported package manager found. Install packages manually."
    MANAGER="none"
fi

if [ "$MANAGER" != "none" ]; then
    echo "==> Installing required packages via $MANAGER..."
    # TODO: Parse packages.yaml required list and install.
    # For now, install the defaults:
    $MANAGER install -y git curl
fi

# ---------------------------------------------------------------------------
# 2. Dotfile deployment
# ---------------------------------------------------------------------------
if [ -d "$DOTFILES_DIR" ]; then
    echo "==> Deploying dotfiles from $DOTFILES_DIR..."
    for src in "$DOTFILES_DIR"/.*; do
        fname="$(basename "$src")"
        # Skip . and ..
        [ "$fname" = "." ] || [ "$fname" = ".." ] && continue
        dest="$HOME/$fname"
        if [ -e "$dest" ]; then
            echo "  SKIP $fname (already exists at $dest)"
        else
            cp -R "$src" "$dest"
            echo "  OK   $fname → $dest"
        fi
    done
else
    echo "  (no dotfiles directory found — skipping)"
fi

# ---------------------------------------------------------------------------
# 3. Concept environment marker
# ---------------------------------------------------------------------------
PRIMA_ENV="$HOME/.prima-env"
if [ ! -f "$PRIMA_ENV" ]; then
    cat > "$PRIMA_ENV" <<EOF
# Prima Terminal Environment
# Auto-generated by bootstrap.sh — edit freely.
PRIMA_CONCEPT="$(grep 'name:' "$PRIMA_DIR/prima.yaml" 2>/dev/null | head -1 | sed 's/.*: *//' | tr -d '"')"
PRIMA_VERSION="$(grep 'version:' "$PRIMA_DIR/prima.yaml" 2>/dev/null | head -1 | sed 's/.*: *//' | tr -d '"')"
PRIMA_ROOT="$PRIMA_DIR"
EOF
    echo "==> Created $PRIMA_ENV"
fi

echo "==> Bootstrap complete. Open a new shell or run: source ~/.prima-env"
